SELECT [invoiceId]
      ,[acaYear]
      ,[semester]
      ,[invoiceNo]
      ,[regisType]
      ,[invoiceAmount]
      ,[paidDate]
      ,[paidAmount]
      ,[paidStatus]
      ,[invoiceType]
      ,[schNameTh]
      ,[remark]
      ,[studentCode]
  FROM [OP_DB].[dbo].[finance_invoice_2025_01_03]