CREATE TABLE student_ic (
    student_code VARCHAR(100) NULL,
    prefix VARCHAR(100) NULL,
    first_name VARCHAR(100) NULL,
    last_name VARCHAR(100) NULL,
    gender VARCHAR(100) NULL,
    nationality VARCHAR(100) NULL,
    resident_type VARCHAR(100) NULL,
    student_fee_type VARCHAR(100) NULL,
    academic_year VARCHAR(100) NULL,
    academic_term VARCHAR(100) NULL,
    admission_type VARCHAR(100) NULL,
    student_type VARCHAR(100) NULL,
    student_status VARCHAR(100) NULL,
    student_status_2 VARCHAR(100) NULL,
    major VARCHAR(100) NULL,
    major_name VARCHAR(100) NULL,
    division VARCHAR(100) NULL,
    division_name VARCHAR(100) NULL,
    is_active VARCHAR(100) NULL,
)