SELECT case when s.TitleId in ('12','17') then '002'
		when s.TitleId in ('26','30') or (TitleId = '44' and s.Code in ('4880635','5380028')) then '003'
		when s.TitleId in ('14','18') then '001'
		else 'Not Specified' end as 'รหัสคำนำหน้าชื่อ'
		,case when s.TitleId in ('17') then 'Mrs.'
		when s.TitleId in ('12','26','30') or (TitleId = '44' and s.Code in ('4880635','5380028')) then 'Ms.'
		when s.TitleId in ('14','18') then 'Mr.'
		else 'Not Specified' end as 'คำนำหน้าชื่อ'
		,UPPER(LTRIM(RTRIM([FirstNameEn]))) 'ชื่อ(ภาษาไทย)'
		,UPPER(LTRIM(RTRIM([MidNameEn]))) 'ชื่อกลาง(ภาษาไทย)'
		,UPPER(LTRIM(RTRIM([LastNameEn]))) 'สกุล(ภาษาไทย)'
		,UPPER(LTRIM(RTRIM([FirstNameEn]))) as 'ชื่อ(ภาษาอังกฤษ)'
		,UPPER(LTRIM(RTRIM([MidNameEn]))) as 'ชื่อกลาง(ภาษาอังกฤษ)'
		,UPPER(LTRIM(RTRIM([LastNameEn]))) as 'สกุล(ภาษาอังกฤษ)'
		,case when Gender = 1 then 'M'
		when Gender = 2 or s.Code = '4880635' then 'F'
		else 'Not Specified' end as 'เพศ'
		,CitizenNumber as 'เลขประจำตัวประชาชน'
		,Passport as 'เลขหนังสือเดินทาง'
		,FORMAT(SWITCHOFFSET(CONVERT(DATETIMEOFFSET, [BirthDate]), '+07:00'),N'dd/MM/yyyy','th-TH') as 'วันเดือนปีเกิด'
		,s.code as 'รหัสนักศึกษา'
		,[รหัสคณะ] = 'IC'
		,Curriculum.Curriculums.AbbreviationEn as 'รหัสหลักสูตร'
		,Curriculum.CurriculumVersions.NameEn
		,[รหัสสาขา] = '-'
        ,[กลุ่ม] = '0'
        ,[ระดับการศึกษา] = 'B'
		,case when StudentStatus = 'prc' then 'passed_all_required_courses' 
		when StudentStatus = 'pa' then 'passed_away' 
		when StudentStatus = 'rs' then 'resigned' 
		when StudentStatus = 'dm' then 'dismissed' 
		when StudentStatus = 's' then 'studying' 
		when StudentStatus = 'la' then 'leave_of_absence' 
		when StudentStatus = 'ex' then 'exchange' 
		when StudentStatus = 'g' then 'graduated' 
		when StudentStatus = 'g1' then 'graduated_with_first_class_honors' 
		when StudentStatus = 'g2' then 'graduated_with_second_class_honors' 
		when StudentStatus = 'np' then 'no_report' 
		when StudentStatus = 'd' then 'deleted'
		when StudentStatus = 'b' then 'blacklist'
		when StudentStatus = 'tr' then 'transferred_to_other_university'
		when StudentStatus = 're' then 'reenter'
		when StudentStatus = 'ra' then 're_admission'
		else 'Others' end as 'สถานภาพนักศึกษา'
   FROM [student].[Students] s 
   left join [student].[CurriculumInformations] c on s.Id = c.StudentId
   inner join Curriculum.CurriculumVersions on Curriculum.CurriculumVersions.Id = c.CurriculumVersionId
   inner join Curriculum.Curriculums on Curriculum.Curriculums.Id = Curriculum.CurriculumVersions.CurriculumId
   where c.IsActive = '1' and (left(s.code,2) > '49' and left(s.code,2) > '99')