CREATE TABLE student_info (
    prefix_id  VARCHAR(3) NOT NULL,
    firstname_th VARCHAR(MAX) NOT NULL,
    middle_name_th VARCHAR(MAX),
    lastname_th VARCHAR(MAX) NOT NULL,
    firstname_en VARCHAR(MAX) NOT NULL,
    middle_name_en VARCHAR(MAX),
    lastname_en VARCHAR(MAX) NOT NULL,
    gender  VARCHAR(1) NOT NULL,
    citizen_id  VARCHAR(MAX) NOT NULL,
    birthday DATE NOT NULL,
    student_id INT NOT NULL,
    faculty_id VARCHAR(MAX) NOT NULL,
    curriculum_id VARCHAR(MAX) NOT NULL,
    major_id VARCHAR(MAX) NOT NULL,
    [group] VARCHAR(2) NOT NULL,
    degree_level VARCHAR(2) NOT NULL,
    education_status VARCHAR(3) NOT NULL,
    nationality VARCHAR(5) NOT NULL,
    admission_type VARCHAR(MAX) NOT NULL,
    remark VARCHAR(MAX) NOT NULL,
)